[mecamanage_servers]
production ansible_host=192.168.1.100 ansible_user=ubuntu ansible_port=22

[mecamanage_servers:vars]
ansible_ssh_private_key_file=~/.ssh/mecamanage_key
ansible_python_interpreter=/usr/bin/python3